export const mockColumns = {
  excelTitle: 'mock LOL数据',
  isFetchAllData: false,
  sheetArray: [
    {
      fetchUrl: 'http://localhost:7777/api/lol/getStatsData',
      fetchOptions: {
        startTime: '1740758400,1743436799',
        teamIds: '',
        LeagueIds: '',
        isBattle: 0,
        pageNumber: 1,
        pageSize: 10,
        regions: '',
        sort: '-start_time',
      },
      sheetName: '表格2',
      columns: [
        {
          title: <span>'战队'</span>,
          key: 'match_name',
          dataIndex: 'match_name',
          width: 17,
        },
        {
          title: '日期',
          key: 'start_time',
          dataIndex: 'start_time',
          width: 16,
        },
        {
          title: '联赛',
          key: 'league_name',
          dataIndex: 'league_name',
          width: 15,
        },
        {
          title: '地图比分',
          key: 'bo_score',
          dataIndex: 'bo_score',
          width: 6.6,
        },
        {
          title: '发生五杀时比分',
          key: 'race_to_5_kills_score',
          dataIndex: 'race_to_5_kills_score',
          width: 11,
        },
        {
          title: '发生十杀时比分',
          key: 'race_to_10_kills_score',
          dataIndex: 'race_to_10_kills_score',
          width: 12,
        },
        {
          title: '杀敌比分（总数）',
          key: 'kills_score',
          dataIndex: 'kills_score',
          width: 13,
        },
        {
          title: '十分钟前比分（总）',
          key: 'mins_10_kills_score',
          dataIndex: 'mins_10_kills_score',
          width: 13,
        },
        {
          title: '二十分钟前比分',
          key: 'mins_20_kills_score',
          dataIndex: 'mins_20_kills_score',
          width: 13,
        },
        {
          title: '最高击杀数（位置）',
          key: 'max_kills_value_role',
          dataIndex: 'max_kills_value_role',
          width: 13,
        },
        {
          title: '辅助位杀敌数（英雄）',
          key: 'role_sup_kills_score',
          dataIndex: 'role_sup_kills_score',
          width: 13,
        },
        {
          title: '中路选手击杀比分',
          key: 'role_mid_kills_score',
          dataIndex: 'role_mid_kills_score',
          width: 13,
        },
        {
          title: 'ADC选手击杀比分',
          key: 'role_adc_kills_score',
          dataIndex: 'role_adc_kills_score',
          width: 13,
        },
        {
          title: '红方最高个人阵亡数',
          key: 'team_1_max_deaths',
          dataIndex: 'team_1_max_deaths',
          width: 10,
        },
        {
          title: '蓝方方最高个人阵亡数',
          key: 'team_2_max_deaths',
          dataIndex: 'team_2_max_deaths',
          width: 10,
        },
        {
          title: '最后被击杀英雄位置',
          key: 'last_killed_role',
          dataIndex: 'last_killed_role',
          width: 18,
        },
        {
          title: '时间',
          key: 'game_time',
          dataIndex: 'game_time',
          width: 11,
        },
        {
          title: '一血时间',
          key: 'first_blood_game_time',
          dataIndex: 'first_blood_game_time',
          width: 11,
        },
        {
          title: '获得一血位置',
          key: 'first_blood_killer_role',
          dataIndex: 'first_blood_killer_role',
          width: 10,
        },
        {
          title: '交出一血位置',
          key: 'first_blood_killed_role',
          dataIndex: 'first_blood_killed_role',
          width: 10,
        },
        {
          title: '三杀',
          key: 'is_triple_kills',
          dataIndex: 'is_triple_kills',
          width: 10,
        },
        {
          title: '四杀',
          key: 'is_quadra_kills',
          dataIndex: 'is_quadra_kills',
          width: 10,
        },
        {
          title: '团灭次数',
          key: 'team_destroyed_count_num',
          dataIndex: 'team_destroyed_count_num',
          width: 10,
        },
        {
          title: '蓝方首选英雄',
          key: 'blue_pick_n_1_champion',
          dataIndex: 'blue_pick_n_1_champion',
          width: 10,
        },
        {
          title: '红方首选英雄',
          key: 'red_pick_n_1_champion',
          dataIndex: 'red_pick_n_1_champion',
          width: 10,
        },
        {
          title: '首队累计5次击杀时最高的杀敌',
          key: 'race_to_5_kills_player_max_kills',
          dataIndex: 'race_to_5_kills_player_max_kills',
          width: 10,
        },
        {
          title: '首队累计10次击杀时最高的杀敌',
          key: 'race_to_10_kills_player_max_kills',
          dataIndex: 'race_to_10_kills_player_max_kills',
          width: 10,
        },
        {
          title: '赢得先机队伍',
          key: 'feats_of_strength_team_name',
          dataIndex: 'feats_of_strength_team_name',
          width: 14,
        },
      ],
      data: [],
    },
    {
      fetchUrl: '',
      fetchOptions: {},
      sheetName: '表格1',
      columns: [
        {
          title: '姓名',
          key: 'name',
          dataIndex: 'name',
          width: 10,
        },
        {
          title: '年龄',
          key: 'age',
          dataIndex: 'age',
          width: 10,
        },
        {
          title: '状态',
          key: 'status',
          dataIndex: 'status',
          width: 10,
        },
      ],
      data: [],
    },
  ],
};
